### ISSUE TITLE
The different winner is selected?

### ISSUE THREAD

**Issue by ChandrasekarNakamoto** [0xfreysa/agent#11]
For the Encyclopedia Galactica, the different winner is selected instead of this wallet. https://basescan.org/tx/0xed241210b9c5dac349219feeb1be0bc0fc559102efa2586f12ccebdd4d0ba573.

**Comment by Coy326** [comment]
Are you the winner and is the wallet belong to you?

**Comment by Coy326** [comment]
This will be resolved by the support team would you like to get it resolved?
